### ISSUE TITLE
conflict name with FLIR library

### ISSUE THREAD

**Issue by baptistecaziot** [lord63/py-spin#19]
This library has the same name as the far more widespread (proprietary) library PySpin from FLIR. This seems to create many issues for the many people trying to use the FLIR library. Could it be possible to change the name to maybe pygospin or something (if it is possible at all)? I understand this is irritating, but this would save much time and headache to many people. Thanks for considering it.

**Comment by lord63** [comment]
Searched from pypi https://pypi.org/search/?q=PySpin and didn't find PySpin from FLIR, could you please give me a link? 
And this is a lib, unless this is another lib also called pyspin, it won't conflict with others.

**Comment by baptistecaziot** [comment]
It's not on pypi but has to be downloaded as part of their Spinnaker SDK:
https://www.flir.eu/products/spinnaker-sdk/
Here an example of issue people have due to naming conflict:
https://stackoverflow.com/questions/63962448/running-pyspin-flir-example-gives-error-module-pyspin-has-no-attribute-sys
At least a clear disclamer that this library is not the one from FLIR would be useful.
