### ISSUE TITLE
@makespin decorator fails to work when function has args/kwargs

### ISSUE THREAD

**Issue by fruch** [lord63/py-spin#7]

**Comment by fruch** [comment]
see #8 , I think I've addressed it there

**Comment by lord63** [comment]
Sorry for the long delay, will check it this weekend.

**Comment by fruch** [comment]
I think you should check #8 I think it's much better approach...

**Comment by ghost** [comment]
I'll probably wait until #9 is merged and then submit a new PR if there are still problems.
